name: Code checks

on:
  push:
    branches:
      - stage
      - main
  pull_request:

jobs:
  check:
    runs-on: ubuntu-latest
    env:
      VITE_TINYMCE_API_KEY: gpl
      VITE_SUPABASE_BUCKET: naruto-effect-public-storage
      VITE_BFF_SUPABASE_URL: http://localhost:54321/
      VITE_SUPABASE_CLIENT_ANON_KEY: token.part.of
      VITE_ADMIN_EMAIL: example@example.xyz
      VITE_LOGIN_PHRASE: test

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Install Bun
        uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: bun install

      - name: Supabase
        uses: supabase/setup-cli@v1
        with:
            version: latest

      - name: Start Supabase and extract keys
        id: supabase
        run: |
          supabase start > output.log &
          SUPABASE_PID=$!
          sleep 10
          kill $SUPABASE_PID
          cat output.log
          ANON_KEY=$(grep -oP 'anon key: \K[^ ]+' output.log)
          echo "VITE_SUPABASE_CLIENT_ANON_KEY=$ANON_KEY" >> $GITHUB_ENV

      - name: Build app
        run: bun run build

      - name: Run checks and tests
        run: |
          bun run check
          bun run check:biome
          bun run test:unit

      - name: E2E Tests
        run: |
          bunx playwright install --with-deps
          bun run test:integration
