name: Code checks

on:
  push:
    branches:
      - stage
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      VITE_TINYMCE_API_KEY: dkasjndjkasndjknasjkndkjasdnmasjkdnyui
      VITE_SUPABASE_BUCKET: bucket-name
      VITE_BFF_SUPABASE_URL: https://url.supabase.co/
      VITE_SUPABASE_CLIENT_ANON_KEY: token.part.of
      VITE_ADMIN_EMAIL: example@example.xyz
      VITE_LOGIN_PHRASE: test

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Install Bun
        uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: bun install

      - name: Build app
        run: bun run build

      - name: Run checks and tests
        run: |
          bun run check
          bun run biome:check
          bun run test:integration
