name: Code checks

on:
  push:
    branches:
      - stage
      - main
  pull_request:

jobs:
  check:
    runs-on: ubuntu-latest
    env:
      VITE_TINYMCE_API_KEY: gpl
      VITE_SUPABASE_BUCKET: naruto-effect-public-storage
      VITE_BFF_SUPABASE_URL: http://localhost:54321/
      VITE_SUPABASE_CLIENT_ANON_KEY: token.part.of
      VITE_ADMIN_EMAIL: example@example.xyz
      VITE_LOGIN_PHRASE: test

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Install Bun
        uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: bun install

      - name: Run checks and tests
        run: |
          bun run check
          bun run check:biome
          bun run test:unit

      - name: Install Playwright
        run: bunx playwright install --with-deps

      - name: Install Supabase
        uses: supabase/setup-cli@v1
        with:
            version: latest

      - name: Start Supabase
        id: supabase
        run: supabase start

      - name: E2E Tests
        run: bun run test:integration
